'use client';
import Head from 'next/head';
import { FC, useEffect, useState } from 'react';

import FadeInOutContainer from '@/components/animated/FadeInOutContainer';
import Explore from '@/components/pages/HomePage/Explore';
import FAQ from '@/components/pages/HomePage/FAQ';
import FindCandidate from '@/components/pages/HomePage/FindCandidate';
import FindToday from '@/components/pages/HomePage/FindToday';
import FindWork from '@/components/pages/HomePage/FindWork';
import Matchminds from '@/components/pages/HomePage/Matchminds';
import { exploreSectionData, matchmindSectionData } from '@/constants/sectionsData/data';
import { getHomePageData } from '@/services/HomePageService';
import { ClientHomePageBlocks } from '@/types/services/HomePageServiceEnteties';

import styles from './styles.module.scss';

const Home: FC = () => {
  const [data, setData] = useState<ClientHomePageBlocks | null>(null);

  useEffect(() => {
    const get = async (): Promise<void> => {
      const res = await getHomePageData();

      if (res.data && res.status) {
        setData(res.data);
      }
    };

    get();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page}>
        <FadeInOutContainer key="home">
          <Matchminds
            content={data?.mainPageCallToActionBlocks || matchmindSectionData.content}
            text={data?.mainPageHeaders[0] || matchmindSectionData.text}
            video={data?.mainPageVideos?.find((el) => el.active)?.video ?? ''}
          />
          <Explore
            content={data?.mainPageFeatures || []}
            text={data?.mainPageFeaturesBlocks[0] || exploreSectionData.text}
          />
          <FindCandidate
            text={data?.mainPageCandidateBlocks[0] || null}
            content={data?.candidateBlockItems || []}
          />
          <FindWork
            text={data?.mainPageCompanyBlocks[0] || null}
            content={data?.companyBlockItems || []}
          />
          <FAQ text={data?.mainPageFaqBlocks[0] || null} content={data?.faqItems || []} />
          <FindToday text={data?.mainPageCallToActionFooters[0] || null} />
        </FadeInOutContainer>
      </div>
    </>
  );
};

export default Home;
